import { Geist, Geist_Mono } from "next/font/google";
//import { Poppins_Bold, Poppins_Reg } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// const poppinsBoldSans = Poppins_Bold({
//   variable: "--font-poppins-bold-sans",
//   subsets: ["latin"],
//   weight: 600,
// });
// const poppinsRegularSans = Poppins_Reg({
//   variable: "--font-poppins-reg-sans",
//   subsets: ["latin"],
//   weight: 300,
// });

export const metadata = {
  title: "iWatch Landingpage",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`bg-[#b6ccda] text-[white] ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
